name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v